version: '3'

services:
  web-app:
    image: tab-lab-web-app
    build: ./web-app
    ports:
      - "4201:4200"
    environment:
        - WEB_API_BASE_URL=http://localhost:3001

  auth:
    image: auth-service
    build: ./auth-service
    ports:
      - "3000:8080"
    environment:
      - JWT_SIGN_SECRET=my_secret
      - DATABASE_CONNECTION_STRING=mongodb://mongo:27017


  web-api:
    image: tab-lab-web-api
    build: ./web-api
    ports:
      - "3001:8080"
    environment: 
      - AUTH=true
      - AUTH_CLIENT_BASE_URL=http://auth:8080
      - DATABASE_CONNECTION_STRING=mongodb://mongo:27017

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports: 
      - "27017:27017"

volumes:
  data: